name: guacamole-service
services:
  guacamole:
    image: flcontainers/guacamole
    container_name: guacamole
    restart: unless-stopped
    volumes:
      - ./config:/config
    ports:
      - 8080:8080
